AWSTemplateFormatVersion: '2010-09-09'
Description: Main CloudFormation template that orchestrates nested stacks for a contact page application

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: The deployment environment
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: ID of the existing company VPC
  
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of existing subnet IDs for deployment (minimum 2 recommended)
  
  TemplateBucket:
    Type: String
    Description: S3 bucket containing nested stack templates

Resources:
  # Security Groups Stack
  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.${AWS::Region}.amazonaws.com/${TemplateBucket}/templates/security-groups.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !Ref VpcId
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # Contact Page Stack
  ContactPageStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.${AWS::Region}.amazonaws.com/${TemplateBucket}/templates/contact-page.yaml
      Parameters:
        Environment: !Ref Environment
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # Load Balancer Stack
  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.${AWS::Region}.amazonaws.com/${TemplateBucket}/templates/load-balancer.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !Ref VpcId
        SubnetIds: !Join [',', !Ref SubnetIds]
        WebServerSecurityGroupId: !GetAtt SecurityGroupsStack.Outputs.WebServerSecurityGroupId
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  WebServerSecurityGroupId:
    Description: Security Group ID for web servers
    Value: !GetAtt SecurityGroupsStack.Outputs.WebServerSecurityGroupId
    Export:
      Name: !Sub ${AWS::StackName}-WebServerSecurityGroupId

  ContactsTableName:
    Description: DynamoDB table for contact information
    Value: !GetAtt ContactPageStack.Outputs.ContactsTableName
    Export:
      Name: !Sub ${AWS::StackName}-ContactsTableName

  ResumeBucketName:
    Description: S3 bucket for resume storage
    Value: !GetAtt ContactPageStack.Outputs.ResumeBucketName
    Export:
      Name: !Sub ${AWS::StackName}-ResumeBucketName

  WebsiteBucketName:
    Description: S3 bucket for website content
    Value: !GetAtt ContactPageStack.Outputs.WebsiteBucketName
    Export:
      Name: !Sub ${AWS::StackName}-WebsiteBucketName

  DeploymentBucketName:
    Description: S3 bucket for deployment artifacts
    Value: !GetAtt ContactPageStack.Outputs.DeploymentBucketName
    Export:
      Name: !Sub ${AWS::StackName}-DeploymentBucketName

  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !GetAtt ContactPageStack.Outputs.ApiEndpoint
    Export:
      Name: !Sub ${AWS::StackName}-ApiEndpoint

  CloudFrontDistributionDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt ContactPageStack.Outputs.CloudFrontDistributionDomainName
    Export:
      Name: !Sub ${AWS::StackName}-CloudFrontDomainName
      
  LoadBalancerDnsName:
    Description: DNS name of the Application Load Balancer
    Value: !GetAtt LoadBalancerStack.Outputs.LoadBalancerDnsName
    Export:
      Name: !Sub ${AWS::StackName}-LoadBalancerDnsName